### PR TITLE
Change type "community" to "community (codecheck)"

### PR DESCRIPTION
**Pull request by angelina-momin**
Discussed with Daniel about changing type "community" to "community (codecheck)" in the `register.csv` file. This is done to easily categorise registers sorted by the venue "community"

### CODE REVIEW

**Comment by sje30** [comment]
hi

cc: @nuest 

for the code checks that we are doing as part of the CODECHECKNL, what would be the preferred name for them?
Ideally, we'd like to be able to categorise these as part of the NL project, so we can easily keep track of our target (40 code checks for the project).

**Comment by angelina-momin** [comment]
@sje30 (and @nuest) in response to your question I noticed that there is a type "CODECHECK NL" in the register.csv file, refer to [this line](https://github.com/codecheckers/register/blob/master/register.csv#L68). 

Is that the type for the code checks done in part of codecheck NL? If so I would suggest we rename it to "community (codecheck NL)" so that with the venue sorted register feature that I will merge soon, after rendering the registers, there will a folder called "community" which will then have subfolders "codecheck" (referring to general codecheck) and "codecheck NL" (referring to code checks done as part of codecheck NL). At the moment the venue sort rendering creates a folder "codecheck_nl" instead of nesting it under "community". 

Let me know what you both think. I will leave the decision of the naming of the type to you both.

**Comment by nuest** [comment]
I support `community (codecheck NL)` to work well with the other PR:

**Review by sje30 — APPROVED** [review]
Thanks, super.

**Comment by sje30** [comment]
merged

**Comment by angelina-momin** [comment]
@sje30 reopening the PR and merging it cause I think you accidentally closed before merging.

**Pull request merged**
